# Generated by Django 3.1.7 on 2021-03-13 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('reseña', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=70)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'Dni'), ('PS', 'Pasaporte')], default='DNI', max_length=3)),
                ('numero_documento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('estado_reserva', models.BooleanField(choices=[(False, 'Pendiente de asignacion'), (True, 'Asignada')], default=False, max_length=9)),
                ('numero_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_de_ingreso', models.DateField()),
                ('fecha_de_egreso', models.DateField()),
                ('cantidad_huespedes', models.IntegerField()),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalCristianGarcia.huesped')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_de_plazas', models.IntegerField()),
                ('numero_habitacion', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('precio_por_noche', models.FloatField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalCristianGarcia.hotel')),
                ('reservas', models.ManyToManyField(blank=True, null=True, to='finalCristianGarcia.Reserva')),
            ],
        ),
    ]
