# Generated by Django 3.1.7 on 2021-03-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalCristianGarcia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_de_egreso',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_de_ingreso',
            field=models.DateField(auto_now_add=True),
        ),
    ]
