# Generated by Django 3.1.7 on 2021-03-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalCristianGarcia', '0002_auto_20210313_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_de_egreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_de_ingreso',
            field=models.DateField(),
        ),
    ]
